"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']

OPTIONS = {
    'includes': {'PySide2.QtCore', 'PySide2.QtUiTools', 'PySide2.QtGui', 'PySide2.QtWidgets'},
    'qt_plugins': [
        'platforms/libqcocoa.dylib',
        'platforms/libqminimal.dylib',
        'platforms/libqoffscreen.dylib',
        'styles/libqmacstyle.dylib'
    ],
    'plist': {
        'CFBundleName': 'Test',
        'CFBundleShortVersionString': '1.0',
        'CFBundleIdentifier': 'org.test.test',
        'LSMinimumSystemVersion': '10.12.0',
        'NSHumanReadableCopyright': 'Copyright © 2021 Alberto Sottile All Rights Reserved',
    }
}

setup(
    app=APP,
    name='Test',
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
